
consent_nat = [
    {
      "consent_form_naturalistic": "<h3><p>DARTMOUTH COLLEGE</p> <p>Naturalistic Cognition</p>  <p>RESEARCH PROJECT INFORMATION SHEET</p></h3>" +
      "<p><small><small>This research project is being conducted by researchers from the Department of Psychological & Brain Sciences at Dartmouth College, Hanover, NH, USA. This study aims to understand how individuals respond to movies and stories, and how their responses relate to aspects of their personality, cognitive abilities, and other traits. </p>" + 
      "Your participation is voluntary. Participation involves watching videos, reading or listening to stories, playing simple video games and other computerized tasks, answering questions about yourself, and similar activities. You may choose to not answer any or all questions concerning personal or demographic information (age, gender, race, ethnicity, location, handedness etc.) as well as your opinions or feelings about the presented photos, audios, videos or any other survey material. However, you may be required to answer third-person questions relating to the task (e.g. Was there a social interaction in the presented video?).  You must be 18 or older to participate. You may immediately end your participation if any aspect of the research procedure makes you too uncomfortable to continue. If you end your participation prematurely due to discomfort or technical difficulties, please contact the researcher to make sure you receive your payment. You may contact the researcher Emily Finn at emily.s.finn@dartmouth.edu.</p>" +
      "The study involves sensitive personal questions about mental health, coping methods, physical health, and emotions such as feelings of depression, anxiety, stress, anger, sadness, fear, paranoia, delusions, self-worth, quality of life, physical aggression, and perceptions of personal relationships and support systems." + 
      "The information collected will be anonymous and no identifying information will be stored with the data collected during the experiment. Identifying information will not be used in any presentation or paper written about this project and such presentations will represent the aggregation of data from groups of people. Because your responses will not be individually identified, we will not be providing you with personal feedback or referrals based on any of your answers. We will not be monitoring your answers to any items, including questions about suicidality and self-harm, either in real time or after your participation is complete. If you are in crisis, and need immediate support or intervention, call, or go the website of the National Suicide Prevention Lifeline (1-800-273-8255). Trained crisis workers are available to talk 24 hours a day, 7 days a week."+
      "Should you contact the research team to indicate discomfort related to questions about self-harm and suicidal ideation, we will be prompted to direct you to the appropriate counseling resources. If you are a current Dartmouth student, we will be contacting Dick’s House on your behalf to connect you with a mental health professional."+
      "For general information on mental health and to locate treatment services in your area, call the Substance Abuse and Mental Health Services Administration (SAMHSA) Treatment Referral Helpline at 1-800-662-HELP (4357). SAMHSA also has a Behavioral Health Treatment Locator on its website that can be searched by location. "+

      "<p>Questions about this project may be directed to: </p> <p> Emily Finn, Principal Investigator, HB 6207 Moore Hall,Hanover, NH 03755. Email: emily.s.finn@dartmouth.edu </p>"+
      "CPHS Approval Date 11/23/2021"

    }
   ]