questions = [
 { //1
   "img": "images/CDK_7_reshaped_2.5.jpeg",
   "ML1": "These old women are currently ",
   "ML2": ". They are feeling ",
   "ML3": ". In the background, there is ",
   "ML1x": "These old women are currently ",
   "ML2x": "They are feeling ",
   "ML3x": "In the background, there is ",
   "input1": ['swimming in the water','swimming across the english channel','swimming in a public pool'],
   "input2": ['cold and slightly nervous about the fog','prideful','distressed as the one on the far right appears to be drowning'],
   "input3": ['a fair or carnival','a ship','a ship heading towards them']
 },
 {//2
   "img": "images/CDK_3_reshaped_2.5.jpeg",
   "ML1": "The man and the young girl are located in a ",
   "ML2": ". He currently is ",
   "ML3": " while, behind him, she is ",
   "ML1x": "The man and the young girl are located in a ",
   "ML2x": "He currently is ",
   "ML3x": "while, behind him, she is ",
   "input1": ['colosseum','museum or landmark','monastery'],
   "input2": ["gazing into the sky",'pondering','pondering'],
   "input3": ['running happily','running or jumping','playing']

 },
 {//3
   "img": "images/CDK_8_reshaped.jpeg",
   "ML1": "This man is a(n) ",
   "ML2": ". He is feeling ",
   "ML3": ". He is addressing a crowd of ",
   "ML1x": "This man is a(n) ",
   "ML2x": "He is feeling ",
   "ML3x": "He is addressing a crowd of ",
   "input1": ['actor playing a politician','politician','cult leader'],
   "input2": ['enthusiastic','ecstatic','empowered'],
   "input3": ['actors playing journalists and other politicians','supporters','followers']

 },
 {//4
   "img": "images/CDK_9_reshaped.jpeg",
   "ML1": "The child is laying down because ",
   "ML2": ". The people around the child are currently ",
   "ML3": ". The man on the left is ",
   "ML1x": "The child is laying down because ",
   "ML2x": "The people around the child are currently ",
   "ML3x": "The man on the left is ",
   "input1": ['he does not feel very well','she is ill','feeling unwell'],
   "input2": ['helping him','praying','scolding his brother'],
   "input3": ['a doctor','the doctor','his father']


 },
 {//5
   "img": "images/CDK_10_reshaped.jpeg",
   "ML1": "The people are standing in/at/on ",
   "ML2": " because ",
   "ML3": ". They are looking at ",
   "ML1x": "The people are standing in/at/on ",
   "ML2x": "because ",
   "ML3x": "They are looking at ",
   "input1": ['an airfield','the tarmac','an airstrip'],
   "input2": ['the rocket is being launched','the president is coming','the president is coming'],
   "input3": ['the rocket','air force one','ongoing plane traffic'],
   "border_color": "#7FFFD4"

 },
 {//6
   "img": "images/CDK_14_reshaped.jpeg",
   "ML1": "This man is a(n) ",
   "ML2": ". He is walking towards ",
   "ML3": " and he feels ",
   "ML1x": "This man is a(n) ",
   "ML2x": "He is walking towards ",
   "ML3x": "and he feels ",
   "input1": ['physiotherapist','art critic','accountant'],
   "input2": ['an asylum','a piece of art','a sculpture'],
   "input3": ['conflicted','small','despair'],
   "border_color": "#F5F5DC"

 },
 {//7
   "img": "images/CDK_16_reshaped.jpeg",
   "ML1": "This is a scene from a ",
   "ML2": ". The people are there in order to ",
   "ML3": ". The man is walking out because he ",
   "ML1x": "This is a scene from a ",
   "ML2x": "The people are there in order to ",
   "ML3x": "The man is walking out because he ",
   "input1": ['movie','church','church'],
   "input2": ['beg','pray','see who wins the case'],
   "input3": ['is not participating','is uncomfortable','lost the case']

 },
 {//8
   "img": "images/CDK_19_reshaped.jpeg",
   "ML1": "These men are a part of ",
   "ML2": " and are setting up ",
   "ML3": " for the purpose of ",
   "ML1x": "These men are a part of ",
   "ML2x": "and are setting up ",
   "ML3x": "for the purpose of ",
   "input1": ['the army','the circus','a stunt group'],
   "input2": ['barricades','for a show','rings of fire'],
   "input3": ['crowd control','entertainment','riding through them']

 },
 {//9
   "img": "images/CDK_20_reshaped.jpeg",
   "ML1": "The old woman is being pulled on a ",
   "ML2": " because ",
   "ML3": ". The driver of the car is thinking about ",
   "ML1x": "The old woman is being pulled on a ",
   "ML2x": "because ",
   "ML3x": "The driver of the car is thinking about ",
  "input1": "paddle",  
   "input2": "she cannot walk",
   "input3": "his family",
   "input1": ['plank','board of wood','sled'],
   "input2": ['it seems fun','she is elderly','cannot walk'],
   "input3": ['why she is on a plank','whether the board will hit his car','offering her a ride']

 },
 {//10
   "img": "images/CM_2_reshaped.jpeg",
   "ML1": "This man is a(n) ",
   "ML2": " and he is sitting by the sea reading the paper because ",
   "ML3": ". He does this in hopes that he ",
   "ML1x": "This man is a(n) ",
   "ML2x": "and he is sitting by the sea reading the paper because ",
   "ML3x": "He does this in hopes that he ",
   "input1": ['politician','professor','shy man'],
   "input2": ['he needs information','it is peaceful','he enjoys doing this during his free time'],
   "input3": ['will get the information that he wants','gets clarity','can escape from the outside world'],
   "border_color": "#8A2BE2"

 },
 {//11
   "img": "images/CDK_4_reshaped_2.5.jpeg",
   "ML1": "This crowd has gathered in order to ",
   "ML2": ". The two upfront are there because they are ",
   "ML3": ". The girls on the board above them are ",
   "ML1x": "This crowd has gathered in order to ",
   "ML2x": "The two upfront are there because they are ",
   "ML3x": "The girls on the board above them are ",
   "input1": ['attend a public event','observe a show','watch a concert'],
   "input2": ['organizers of the event','late','excited'],
   "input3": ['in an advertisement for a dance school','trying to get down','the main actors'],
   "border_color": "#ff6347"

 },
 {//12
   "img": "images/CDK_6_reshaped.jpeg",
   "ML1": "These children are playing in/on a(n) ",
   "ML2": ". The girl is ",
   "ML3": " while the boy is ",
   "ML1x": "These children are playing in/on a(n) ",
   "ML2x": "The girl is ",
   "ML3x": "while the boy is ",
   "input1": ['construction site','cesspit','park'],
   "input2": ['playing with a pump','driving','biking'],
   "input3": ['concentrating on something','daydreaming','fiddling around']

 },
 {//13
   "img": "images/CM_3_reshaped.jpeg",
   "ML1": "This little girl is in ",
   "ML2": ". The statues around her represent ",
   "ML3": ". The picture is being taken by ",
   "ML1x": "This little girl is in ",
   "ML2x": "The statues around her represent ",
   "ML3x": "The picture is being taken by ",
   "input1": ['her garden','church','Winchester'],
   "input2": ['the Virgin Mary','angels','wealth'],
   "input3": ['her mother','her mother','the Lord'],
   "border_color": "#5F9EA0"

 },
 {//14
   "img": "images/DH_1_reshaped.jpeg",
   "ML1": "The people are gathered at/for a(n) ",
   "ML2": ". The man is catching the balloon because ",
   "ML3": " and is feeling ",
   "ML1x": "The people are gathered at/for a(n) ",
   "ML2x": "The man is catching the balloon because ",
   "ML3x": "and is feeling ",
   "input1": ['party','dinner','wedding'],
   "input2": ['it came his way','someone threw it at him','a child threw it at him'],
   "input3": ['happy','happy','giddy'],
   "border_color": "#D2691E"

 },
 {//15
   "img": "images/DH_2_reshaped.jpeg",
   "ML1": "This is a group of ",
   "ML2": " who are currently at ",
   "ML3": ". They are responding to a(n) ",
   "ML1x": "This is a group of ",
   "ML2x": "who are currently at ",
   "ML3x": "They are responding to a(n) ",
   "input1": ['people','singers','singers'],
   "input2": ['a protest','choir practice','a theater'],
   "input3": ['speaker','instructor','command from the orchestra director'],
   "border_color": "#FF7F50"

 },
 {//16
   "img": "images/DH_3_reshaped.jpeg",
   "ML1": "These men are sitting down to ",
   "ML2": ". They are thinking about ",
   "ML3": ". The people above in the right-hand corner are there because ",
   "ML1x": "These men are sitting down to ",
   "ML2x": "They are thinking about ",
   "ML3x": "The people above in the right-hand corner are there because ",
   "input1": ['have a drink','to talk','drink'],
   "input2": ['their friends','women','alcohol'],
   "input3": ['they are being remembered','they are a figment of his imagination','they also want a drink'],
   "border_color": "#6495ED"

 },
 {//17
   "img": "images/DH_4_reshaped.jpeg",
   "ML1": "A sailor and a boy are standing by ",
   "ML2": ". The sailor is there in order to ",
   "ML3": ". Behind the pillar, the kid is thinking about ",
   "ML1x": "A sailor and a boy are standing by ",
   "ML2x": "The sailor is there in order to ",
   "ML3x": "Behind the pillar, the kid is thinking about ",
   "input1": ['the entrance of a theater','an information board','a museum'],
   "input2": ['meet a date','read about the president','visit during his leave from a ship'],
   "input3": ['the movies','a way to sneak around the sailor without being noticed','asking his mom to buy him a ticket']
 },
 {//18
   "img": "images/DH_5_reshaped.jpeg",
   "ML1": "The woman is walking towards ",
   "ML2": ". This man is trying to ",
   "ML3": ". His presence makes her feel ",
   "ML1x": "The woman is walking towards ",
   "ML2x": "This man is trying to ",
   "ML3x": "His presence makes her feel ",
   "input1": ['a store','the building','the lobby'],
   "input2": ['hold the door open','get her attention','open the door for her'],
   "input3": ['happy','uncomfortable','safe']
 },
//  {//19 // REPEATED!?!?
//   "img": "images/DH_5_reshaped.jpeg",
//   "ML1": "The woman is walking towards ",
//   "ML2": ". This man is trying to ",
//   "ML3": ". His presence makes her feel ",
//   "input1": ['','',''],
//   "input2": ['','',''],
//   "input3": ['','',''],
//   "border_color": "#A9A9A9"

// },
//  {//19
//    "img": "images/DH_7_reshaped.jpeg", // FIX THIS TWO REPEATED
//    "ML1": "This girl is a ",
//    "ML2": "who is currently located in/at ",
//    "ML3": ". who is currently located in/at ",
//    "input1": ['','',''],
//    "input2": ['','',''],
//    "input3": ['','','']
// },
 {//20
   "img": "images/DH_10_reshaped.jpeg",
   "ML1": "These people are out in the streets in order to ",
   "ML2": ". The man is lifting ",
   "ML3": ". Both women are looking out at the ",
   "ML1x": "These people are out in the streets in order to ",
   "ML2x": "The man is lifting ",
   "ML3x": "Both women are looking out at the ",
   "input1": ['protest','celebrate the coming home of some famous pioneers or something','see someone speak publicly'],
   "input2": ['his wife','his girlfriend','the woman'],
   "input3": ['manifestation','hero or pioneer','stage'],
   "border_color": "#006400"

 },
 {//21
   "img": "images/DH_12_reshaped.jpeg",
   "ML1": "This man is carrying a ",
   "ML2": " for ",
   "ML3": " because ",
   "ML1x": "This man is carrying a ",
   "ML2x": "for ",
   "ML3x": "because ",
   "input1": ['bunny','teddy bear','teddy bear'],
   "input2": ['his wife','his child','his child'],
   "input3": ['he wants to reconcile','that child is gravely sick','it is her birthday']

 },
 {//22
   "img": "images/DH_13_reshaped.jpeg",
   "ML1": "This ",
   "ML2": " is currently standing in/at/by ",
   "ML3": ". He is trying to ",
   "ML1x": "This ",
   "ML2x": "is currently standing in/at/by ",
   "ML3x": "He is trying to ",
   "input1": ['person','industrial worker','man'],
   "input2": ['building','a crumbling factory','a spaceship'],
   "input3": ['stop something from falling on him','find any person needing help','yell at someone']
 },
 {//23
   "img": "images/DH_14_reshaped.jpeg",
   "ML1": "This group of people is here as part of a(n) ",
   "ML2": " in order to ",
   "ML3": ". They are feeling ",
   "ML1x": "This group of people is here as part of a(n) ",
   "ML2x": "in order to ",
   "ML3x": "They are feeling ",
   "input1": ['yoga course','exercising group','class'],
   "input2": ['better their health','stretch','exercise'],
   "input3": ['relaxed','namaste','relaxed']
 },

 {//24
   "img": "images/EE_1_reshaped.jpeg",
   "ML1": "This museum has two paintings next to each other. One painting is ",
   "ML2": " as compared to the other. The men are standing together because ",
   "ML3": ", while the woman is alone because ",
   "ML1x": "This museum has two paintings next to each other. One painting is ",
   "ML2x": "as compared to the other. The men are standing together because ",
   "ML3x": "while the woman is alone because ",
   "input1": ['clothed','better','a copy'],
   "input2": ['the woman in that painting is naked','they saw other men standing there','they are in a tour group'],
   "input3": ['her painting is clothed','appreciates something about the other painting','she is a solo visitor']

 },
 {//25
   "img": "images/EE_2_reshaped.jpeg",
   "ML1": "These people are at a(n) ",
   "ML2": ". They are discussing ",
   "ML3": " while the poodle looks at ",
   "ML1x": "These people are at a(n) ",
   "ML2x": "They are discussing ",
   "ML3x": "while the poodle looks at ",
   "input1": ['conference','dog show','exhibition'],
   "input2": ['the entertainment business','which dog is the best','contestants'],
   "input3": ['another dog','the other dogs','a cat']

 },
 {//26
   "img": "images/EE_3_reshaped.jpeg",
   "ML1": "The kids in the window are ",
   "ML2": ". Outside, there is a(n)/the ",
   "ML3": " passing by. Because of this, the kids are feeling ",
   "ML1x": "The kids in the window are ",
   "ML2x": "Outside, there is a(n)/the ",
   "ML3x": "passing by. Because of this, the kids are feeling ",
   "input1": ['poor','playing','checking the commotion outside'],
   "input2": ['float','balloon','giant Pink Panther'],
   "input3": ['excited','intrigued','slightly fearful of the giant figure'],
   "border_color": "#9932CC"

 },
 {//27
   "img": "images/EE_7_reshaped.jpeg",
   "ML1": "These three came to the museum in order to ",
   "ML2": ". The paper in the empty frame says ",
   "ML3": ". As they inspect it, they start to think about ",
   "ML1x": "These three came to the museum in order to ",
   "ML2x": "The paper in the empty frame says ",
   "ML3x": "As they inspect it, they start to think about ",
   "input1": ['appreciate art','learn','view artwork'],
   "input2": ['"paper"','will return soon','the artwork has been stolen'],
   "input3": ['the meaning of art','where it has gone','the crime']
 },
 {//28
   "img": "images/EE_9_reshaped.jpeg",
   "ML1": "This couple is outside a/the ",
   "ML2": " waiting for ",
   "ML3": ". The man next to them has just ",
   "ML1x": "This couple is outside a/the ",
   "ML2x": "waiting for ",
   "ML3x": "The man next to them has just ",
   "input1": ['chapel','city hall','wedding room'],
   "input2": ['to get married','the clerk to wed them','their marriage'],
   "input3": ['told them he is the lover of the bride getting married before them'
   ,'gone through a legal proceeding',
   'gotten divorced']

 },
 {//29
   "img": "images/EE_10_reshaped.jpeg",
   "ML1": "This is a group of ",
   "ML2": " standing outside of their offices for ",
   "ML3": ". They are looking at ",
   "ML1x": "This is a group of ",
   "ML2x": "standing outside of their offices for ",
   "ML3x": "They are looking at ",
   "input1": ['science professors','doctors','doctors'],
   "input2": ['promotional shoot','a group photo','inspection'],
   "input3": ['a campus photographer','the camera','the new patients']

 },

 {//30
   "img": "images/EE_12_reshaped.jpeg",
   "ML1": "This is located outside of ",
   "ML2": ". People come to this place because they are ",
   "ML3": ". They are gathered because they are waiting for ",
   "ML1x": "This is located outside of ",
   "ML2x": "People come to this place because they are ",
   "ML3x": "They are gathered because they are waiting for ",
   "input1": ['a school','a parking lot','a park'],
   "input2": ['lost','angry','looking for lost family members'],
   "input3": ['their kids','an authority','the parents or relatives to come after the child'],


 },

 
 {//31
   "img": "images/EE_14_reshaped.jpeg", // FIX
   "ML1": "This man and woman are at a(n) ",
   "ML2": ". They met ",
   "ML3": " and are discussing the ",
   "ML1x": "This man and woman are at a(n) ",
   "ML2x": "They met ",
   "ML3x": "and are discussing the ",
   "input1": ['museum','museum','lab'],
   "input2": ['at school','there','each other because they are scientists'],
   "input3": ['history behind the mummies','way she was impeding his way','dead people'],

 },

 {//32
   "img": "images/EE_15_reshaped.jpeg",
   "ML1": "The young boy is looking out at ",
   "ML2": ". He is feeling ",
   "ML3": " as he looks through a window that has been cracked by ",
   "ML1x": "The young boy is looking out at ",
   "ML2x": "He is feeling ",
   "ML3x": "as he looks through a window that has been cracked by ",
   "input1": ['the remnants of the only home he has ever known','us','the broken window'],
   "input2": ['sad and hopeless','sad','normal'],
   "input3": ['a bullet or shrapnel','a stranger','a rock']
 },

 {//33
   "img": "images/EE_16_reshaped.jpeg",
   "ML1": "This woman just walked into a ",
   "ML2": ". The figures standing in her way are ",
   "ML3": " and she is currently ",
   "ML1x": "This woman just walked into a ",
   "ML2x": "The figures standing in her way are ",
   "ML3x": "and she is currently ",
   "input1": ['store','casino','shop'],
   "input2": ['mannequins','slot machines','angry'],
   "input3": ['shopping','playing','not bothered']
 },
 {//34
   "img": "images/EE_17_reshaped.jpeg", 
   "ML1": "The young boy is standing on the back of the tram because ",
   "ML2": ". The tram is stopped due to ",
   "ML3": ". The two people looking out from the back of the tram are wondering ",
   "ML1x": "The young boy is standing on the back of the tram because ",
   "ML2x": "The tram is stopped due to ",
   "ML3x": "The two people looking out from the back of the tram are wondering ",
   "input1": ['he does not have enough money to ride it','he has no ticket','he is a worker'],
   "input2": ['arriving at a stop and it needs to drop off passengers','traffic','technical issues'],
   "input3": ['why the boy is there','if the boy can stay on','when it will be fixed and why a young boy has to fix it']
 },

 {//35 
   "img": "images/HCB_2_reshaped.jpeg", // FIX
   "ML1": "These two men know each other from ",
   "ML2": ". They are staring down at the track because ",
   "ML3": ". They are feeling ",
   "ML1x": "These two men know each other from ",
   "ML2x": "They are staring down at the track because ",
   "ML3x": "They are feeling ",
   "input1": ['the mafia','the military','work'],
   "input2": ['they set a bomb','they are watching the trains','they are watching for a train'],
   "input3": ['deviant','happy','excited']
 },
 {//36
   "img": "images/HCB_3_reshaped.jpeg",
   "ML1": "After ",
   "ML2": ", these two men are lying down in a field. The one closest to us is ",
   "ML3": " while the man behind him is feeling ",
   "ML1x": "After ",
   "ML2x": "these two men are lying down in a field. The one closest to us is ",
   "ML3x": "while the man behind him is feeling ",
   "input1": ['a fight','a visit to a bar','the battle'],
   "input2": ['resting','very tired from working before','dead'],
   "input3": ['defeated','happily drunk','sad']
 },

 {//37
   "img": "images/HCB_4_reshaped.jpeg", // FIX
   "ML1": "This small child is ",
   "ML2": " near the wall behind him which is covered in ",
   "ML3": ". He looks like he is experiencing ",
   "ML1x": "This small child is ",
   "ML2x": "near the wall behind him which is covered in ",
   "ML3x": "He looks like he is experiencing ",
   "input1": ['dancing','standing','tired'],
   "input2": ['paint','a band of black paint','paint'],
   "input3": ['euphoria','joy','tiredness']
 },

 {//38
   "img": "images/HCB_5_reshaped.jpeg",
   "ML1": "The two men are facing the wall because they are currently ",
   "ML2": ". The man with the mustache is looking at ",
   "ML3": ", while the other man is thinking about ",
   "ML1x": "The two men are facing the wall because they are currently ",
   "ML2x": "The man with the mustache is looking at ",
   "ML3x": "while the other man is thinking about ",
   "input1": ['under arrest','looking through','playing hide and seek with their kids'],
   "input2": ['a police officer','a woman','his children'],
   "input3": ['how to escape','the other side','his next hiding place']
 },  

 {//39
   "img": "images/HCB_6_reshaped.jpeg",
   "ML1": "These children are located in/at ",
   "ML2": ". They are there because they ",
   "ML3": " while the man in the suit walks because he wants to ",
   "ML1x": "These children are located in/at ",
   "ML2x": "They are there because they ",
   "ML3x": "while the man in the suit walks because he wants to ",
   "input1": ['school','juvenile prison','a public place'],
   "input2": ['are learning','offended','playing'],
   "input3": ['get to the classroom','teach them','go to the other side']
 },
 {//40
   "img": "images/HCB_7_reshaped.jpeg",
   "ML1": "This man is sitting next to a bin of ",
   "ML2": " because ",
   "ML3": ". Above him is a ",
   "ML1x": "This man is sitting next to a bin of ",
   "ML2x": "because ",
   "ML3x": "Above him is a ",
   "input1": ['beer','apples','fruit'],
   "input2": ['he is an alcoholic','he is selling them','he is eating'],
   "input3": ['defacement that looks like him','drawing of a chicken','face']
 }, 
 {//41
   "img": "images/HCB_9_reshaped.jpeg",
   "ML1": "The man peering out from the door in the foreground is currently ",
   "ML2": ", as the man in the background is trying to ",
   "ML3": ". This is taking place in/at a ",
   "ML1x": "The man peering out from the door in the foreground is currently ",
   "ML2x": "as the man in the background is trying to ",
   "ML3x": "This is taking place in/at a ",
   "input1": ['looking at the man in the background','looking for one girl','watching'],
   "input2": ['escape','kill one guy','sneak in'],
   "input3": ['work camp','house','train station']
 }, 
 {//42
   "img": "images/HCB_10_reshaped.jpeg",
   "ML1": "A group of ",
   "ML2": " is in front of a building. The woman on the left is currently ",
   "ML3": " while the person in the middle is thinking about ",
   "ML1x": "A group of ",
   "ML2x": "is in front of a building. The woman on the left is currently ",
   "ML3x": "while the person in the middle is thinking about ",
   "input1": ['clowns','women','women'],
   "input2": ['measuring','posing','hairdressing'],
   "input3": ['his hair','how this picture looks','how she looks']
 },
 {//43
   "img": "images/HCB_11_reshaped.jpeg",
   "ML1": "The two boys are in/at ",
   "ML2": ". The boy on the right is thinking about ",
   "ML3": " as he looks at the younger boy on the left, who is ",
   "ML1x": "The two boys are in/at ",
   "ML2x": "The boy on the right is thinking about ",
   "ML3x": "as he looks at the younger boy on the left, who is ",
   "input1": ['ruins','an old street','an alleyway'],
   "input2": ['history','playing','keeping his brother safe'],
   "input3": ['playing','running','playing']
 }, 
 {//44
   "img": "images/HCB_12_reshaped.jpeg",
   "ML1": "This man is a(n) ",
   "ML2": ", which explains his many birds. For the last 20 years, he has been ",
   "ML3": ". He is located in ",
   "ML1x": "This man is a(n) ",
   "ML2x": "which explains his many birds. For the last 20 years, he has been ",
   "ML3x": "He is located in ",
   "input1": ['artist','old man','seller'],
   "input2": ['drawing trying to perfect his work','lonely','selling birds'],
   "input3": ['a city on a roof','his home','Tampa']
 }, 
 {//45
   "img": "images/HCB_19_reshaped.jpeg",
   "ML1": "The elderly woman is pointing to indicate ",
   "ML2": ". She is feeling ",
   "ML3": ". She is wearing the American flag to ",
   "ML1x": "The elderly woman is pointing to indicate ",
   "ML2x": "She is feeling ",
   "ML3x": "She is wearing the American flag to ",
   "input1": ['she wants someone to leave','a house','a problem'],
   "input2": ['patriotic','unappreciated','upset'],
   "input3": ['show her patriotism','show her love for her country','protest']
 }, 
 {//46
   "img": "images/HCB_20_reshaped.jpeg",
   "ML1": "These people are gathered because ",
   "ML2": ". They are looking out at a ",
   "ML3": ". The person is on the ground because he ",
   "ML1x": "These people are gathered because ",
   "ML2x": "They are looking out at a ",
   "ML3x": "The person is on the ground because he ",
   "input1": ['they are scared','of a rally','they are watching a performance'],
   "input2": ['dead person','speaker','group of actors'],
   "input3": ['is dead','fell asleep','has fallen off the ledge'],
 }, 
 {//47
   "img": "images/HCB_21_reshaped.jpeg",
   "ML1": "This group of ",
   "ML2": " is in/at a ",
   "ML3": ". They are hoping to ",
   "ML1x": "This group of ",
   "ML2x": "is in/at a ",
   "ML3x": "They are hoping to ",
   "input1": ['refugees','people','kids'],
   "input2": ['camp','line','room'],
   "input3": ['saved','make it to the front before the place closes or runs out','get food'],
 }, 
 {//48
  "img": "images/HCB_22_reshaped.jpeg",
  "ML1": "These two men are in/at ",
  "ML2": ". The man in the back left is currently thinking about ",
  "ML3": " while the man sitting down is feeling ",
  "ML1x": "These two men are in/at ",
  "ML2x": "The man in the back left is currently thinking about ",
  "ML3x": "while the man sitting down is feeling ",
  "input1": ['home','ramen shop','canteen'],
  "input2": ['the day','money','his wife'],
  "input3": ['hungry','satisfied','happy'],
}, 
 {//49
   "img": "images/HCB_24_reshaped.jpeg",
   "ML1": "This group of people is currently ",
   "ML2": " because ",
   "ML3": " is occurring. They are feeling ",
   "ML1x": "This group of people is currently ",
   "ML2x": "because ",
   "ML3x": "is occurring. They are feeling ",
   "input1": ['celebrating','running away','running'],
   "input2": ['rain','something bad','a game'],
   "input3": ['happy','scared','playful']
 }, 
 {//50
   "img": "images/HCB_25_reshaped.jpeg",
   "ML1": "This group of ",
   "ML2": " is standing on/at a ",
   "ML3": ". They have gone there in order to ",
   "ML1x": "This group of ",
   "ML2x": "is standing on/at a ",
   "ML3x": "They have gone there in order to ",
   "input1": ['woman','pilgrims','ghosts'],
   "input2": ['cliff','church','slope'],
   "input3": ['pray','pray','see mountains'],
 },
 {//51
   "img": "images/HCB_26_reshaped.jpeg",
   "ML1": "These people are part of ",
   "ML2": ". They are holding ",
   "ML3": " because ",
   "ML1x": "These people are part of ",
   "ML2x": "They are holding ",
   "ML3x": "because ",
   "input1": ['a group working','a tribe','a fishing group'],
   "input2": ['blankets','blankets','nets'],
   "input3": ['they are collecting salt','they need warmth','they are fishing'],
 },
 {//52
   "img": "images/HCB_29_reshaped.jpeg",
   "ML1": "This child is carrying a portrait of ",
   "ML2": ". He is carrying it to ",
   "ML3": " because he wants to ",
   "ML1x": "This child is carrying a portrait of ",
   "ML2x": "He is carrying it to ",
   "ML3x": "because he wants to ",
   "input1": ['some lady','his grandmother','a random lady'],
   "input2": ['sell it','his house','his den'],
   "input3": ['earn some money','hang it up','decorate his den'],
 },
 {//53
   "img": "images/HCB_31_reshaped.jpeg",
   "ML1": "These two women are ",
   "ML2": " who are looking out from ", //got rid of the s since now presenting it
   "ML3": ". The woman on the left is about to ",
   "ML1x": "These two women are ",
   "ML2x": "who are looking out from ", //got rid of the s since now presenting it
   "ML3x": "The woman on the left is about to ",
   "input1": ['exiles','prostitutes','actresses'],
   "input2": ['jail','a brothel','a foreign land'],
   "input3": ['cry','speak','laugh'],
 },
 {//54
   "img": "images/HCB_32_reshaped.jpeg",
   "ML1": "The five women have gathered because ",
   "ML2": ". They are in/at ", 
   "ML3": ". They are feeling ",
   "ML1x": "The five women have gathered because ",
   "ML2x": "They are in/at ", 
   "ML3x": "They are feeling ",
   "input1": ['of a funeral','of a show','they are mourning'],
   "input2": ['mourning','theatre','church'],
   "input3": ['grief','sad','disenchanted'],
 },
 {//55
   "img": "images/HCB_33_reshaped.jpeg",
   "ML1": "The man is in the cell because ",
   "ML2": ". He just saw/heard ",
   "ML3": " and is reacting by ",
   "ML1x": "The man is in the cell because ",
   "ML2x": "He just saw/heard ",
   "ML3x": "and is reacting by ",
   "input1": ['he is an inmate','he committed a crime','he was drunk'],
   "input2": ['commotion','an injustice','a police officer'],
   "input3": ['reaching out','doing a dance','yelling at the officer']
 },
 {//56
   "img": "images/JK_3_reshaped.jpeg",
   "ML1": "A young man is standing by the road and is ",
   "ML2": " at/to the soldiers. The soldiers are thinking ",
   "ML3": ". They are there because ",
   "ML1x": "A young man is standing by the road and is ",
   "ML2x": "at/to the soldiers. The soldiers are thinking ",
   "ML3x": "They are there because ",
   "input1": ['yelling','shouting','yelling'],
   "input2": ['it is hot','that they do not want to go to war','of home'],
   "input3": ['they work on the railroad','they are going to war','they are going to war']
 },
 {//57
   "img": "images/JK_5_reshaped.jpeg",
   "ML1": "This man is with the horse because ",
   "ML2": ". He is currently telling the horse that ",
   "ML3": " and feels that ",
   "ML1x": "This man is with the horse because ",
   "ML2x": "He is currently telling the horse that ",
   "ML3x": "and feels that ",
   "input1": ['it is his','he is the only thing he has','it can win'],
   "input2": ['it is going to do a race','he likes him','he likes him too'],
   "input3": ['it can win','he likes him too','things will change']
 },
 {//58
   "img": "images/JK_7_reshaped.jpeg",
   "ML1": "This group of people is a(n) ",
   "ML2": " who is being photographed because ",
   "ML3": ". The little girl is in the middle because ",
   "ML1x": "This group of people is a(n) ",
   "ML2x": "who is being photographed because ",
   "ML3x": "The little girl is in the middle because ",
   "input1": ['group of students','family','family'],
   "input2": ['they achieved something','of poverty reportage','they wanted a family photo'],
   "input3": ['she is the one who achieved it','she feels beautiful','they are getting ready to take the photo'],

 },
 {//59
   "img": "images/JK_8_reshaped.jpeg",
   "ML1": "In the foreground, a man is ",
   "ML2": ". Behind him, the line of people consists of ",
   "ML3": ". They are there because they ",
   "ML1x": "In the foreground, a man is ",
   "ML2x": "Behind him, the line of people consists of ",
   "ML3x": "They are there because they ",
   "input1": ['handcuffed','handcuffed','alone'],
   "input2": ['slaves','soldiers','men'],
   "input3": ['are being freed','are watching','are curious'],

 },
 {//60
   "img": "images/JK_9_reshaped.jpeg",
   "ML1": "The nun is telling the little girl that she ",
   "ML2": ". On the side, holding his hat is ",
   "ML3": ". He is there in order to ",
   "ML1x": "The nun is telling the little girl that she ",
   "ML2x": "On the side, holding his hat is ",
   "ML3x": "He is there in order to ",
   "input1": ['is in trouble','should behave','will stay there'],
   "input2": ['a serious man','her grandpa','her dad'],
   "input3": ['supervise','take her home','leave her'],

 },
 {//61
   "img": "images/JK_10_reshaped.jpeg", //TRY
   "ML1": "The person is a(n) ",
   "ML2": " who is in deep thought about ",
   "ML3": ". They are walking down the street towards ",
   "ML1x": "The person is a(n) ",
   "ML2x": "who is in deep thought about ",
   "ML3x": "They are walking down the street towards ",
   "input1": ['pastor','person','woman'],
   "input2": ['life','life','the weather'],
   "input3": ['the church','a bridge','home'],

 },
 {//62
   "img": "images/JK_11_reshaped.jpeg",
   "ML1": "These four men are in a(n) ",
   "ML2": " and are all currently ",
   "ML3": ". They are looking away from the camera because they ",
   "ML1x": "These four men are in a(n) ",
   "ML2x": "and are all currently ",
   "ML3x": "They are looking away from the camera because they ",
   "input1": ['trench','alley','concentration camp'],
   "input2": ['peeing','peeing','posing and pretending to investigate the happenings at the camp because they are political figures'],
   "input3": ['are publicly urinating','do not want to be seen','they thought it would add to the solemness and emotional appeal'],

 },
 {//63
   "img": "images/JK_12_reshaped.jpeg",
   "ML1": "This is a group of ",
   "ML2": ". They are all on this rocky beach holding sticks because they have just finished ",
   "ML3": ". They are feeling ",
   "ML1x": "This is a group of ",
   "ML2x": "They are all on this rocky beach holding sticks because they have just finished ",
   "ML3x": "They are feeling ",
   "input1": ['men','tourists','coal miners'],
   "input2": ['hiking','working','buring the dead'],
   "input3": ['exhausted','tired','nothing'],

 },
 {//64
   "img": "images/JK_13_reshaped.jpeg",
   "ML1": "A young boy is dressed in an angel costume because ",
   "ML2": ". He is on his way to/from ",
   "ML3": " and is talking to ",
   "ML1x": "A young boy is dressed in an angel costume because ",
   "ML2x": "He is on his way to/from ",
   "ML3x": "and is talking to ",
   "input1": ['of Halloween','he likes to dress up','he is in a parade'],
   "input2": ['trick or treating','work','a church'],
   "input3": ['an old lady','his neighbor','a family friend'],

 },
 {//65
   "img": "images/JK_2_reshaped.jpeg",
   "ML1": "This is a group of ",
   "ML2": ". Most of them are feeling ",
   "ML3": " and are expressing their opinions about ",
   "ML1x": "This is a group of ",
   "ML2x": "Most of them are feeling ",
   "ML3x": "and are expressing their opinions about ",
   "input1": ['refugees','people','citizens'],
   "input2": ['afraid','interested','dissatisfied'],
   "input3": ['immigration','law','the government'],

 },
 {//66
   "img": "images/JK_14_reshaped_2.5.jpeg",
   "ML1": "This is a group of ",
   "ML2": ". The two people standing are ",
   "ML3": " while the person lying down is ",
   "ML1x": "This is a group of ",
   "ML2x": "The two people standing are ",
   "ML3x": "while the person lying down is ",
   "input1": "circus performers",
   "input2": "rehearsing",
   "input3": "taking a break",
   "input1": ['friends','actors','friends'],
   "input2": ['playing a game','thieves','a couple'],
   "input3": ['trying to relax on the grass','a farmer','the best friend'],

 },
 {//67
   "img": "images/PJG_1_reshaped_2.5.jpeg",
   "ML1": "The boy is standing in rubble caused by ",
   "ML2": ". He is holding up the stone to ",
   "ML3": " because he is feeling ",
   "ML1x": "The boy is standing in rubble caused by ",
   "ML2x": "He is holding up the stone to ",
   "ML3x": "because he is feeling ",
   "input1": ['time','a storm','war'],
   "input2": ['throw','throw on the piano','throw'],
   "input3": ['playful','angry','helpless'],

 },
 {//68
   "img": "images/PJG_2_reshaped.jpeg",
   "ML1": "These kids are looking at ",
   "ML2": ". The one in the middle is wondering ",
   "ML3": ". The boy on the right is holding up his fingers because ",
   "ML1x": "These kids are looking at ",
   "ML2x": "The one in the middle is wondering ",
   "ML3x": "The boy on the right is holding up his fingers because ",
   "input1": ['a parent','the old man','the camera'],
   "input2": ['why are you taking this picture','why he is taking a picture of them','what is going on'],
   "input3": ['he is three years old','he is posing','he is eating'],

 },
 {//69
   "img": "images/PJG_3_reshaped.jpeg",
   "ML1": "The men on the left are discussing ",
   "ML2": ". The men on the right are discussing ",
   "ML3": ". The boy in the center is feeling ",
   "ML1x": "The men on the left are discussing ",
   "ML2x": "The men on the right are discussing ",
   "ML3x": "The boy in the center is feeling ",
   "input1": ['finance','women','about the events in the neighborhood'],
   "input2": ['the women across the road','about football','strategies for a betting game'],
   "input3": ['awkward','cool','out of place among the men beside him'],

 },
 {//70
   "img": "images/PJG_4_reshaped.jpeg",
   "ML1": "A(n) ",
   "ML2": " is talking to ",
   "ML3": ". Despite his circumstances, he is telling him to ",
   "ML1x": "A(n) ",
   "ML2x": "is talking to ",
   "ML3x": "Despite his circumstances, he is telling him to ",
   "input1": ['photographer','miner','senior citizen'],
   "input2": ['his supervisor','his boss','a coal miner'],
   "input3": ['go back outside and continue getting more pictures','get back to work','take the risk and leave their small town to actually do something with his incredible musical talents'],

 },
 {//71
   "img": "images/PJG_5_reshaped.jpeg",
   "ML1": "This is taking place at/in ",
   "ML2": ". The man in front is there in order to ",
   "ML3": " while the men in the robes around him are ",
   "ML1x": "This is taking place at/in ",
   "ML2x": "The man in front is there in order to ",
   "ML3x": "while the men in the robes around him are ",
   "input1": ['someone\'s lawn','a family home','the cult '],
   "input2": ['see his house','provide direction','try and escape'],
   "input3": ['blessing his house','facilitating a religious practice','casting a spell'],

 },
 {//72
   "img": "images/PJG_6_reshaped.jpeg",
   "ML1": "The woman mowing her lawn is feeling ",
   "ML2": " because the man crouched down in front of her is waiting to ",
   "ML3": ". The man is feeling ",
   "ML1x": "The woman mowing her lawn is feeling ",
   "ML2x": "because the man crouched down in front of her is waiting to ",
   "ML3x": "The man is feeling ",
   "input1": ['confused','protected','relaxed'],
   "input2": ['kill his target','shoot someone','protect her'],
   "input3": ['bored','active','worried'],

 },
 {//73
   "img": "images/PJG_8_reshaped.jpeg",
   "ML1": "These young children are standing behind the fence of a(n) ",
   "ML2": " because they are ",
   "ML3": ". They are all feeling ",
   "ML1x": "These young children are standing behind the fence of a(n) ",
   "ML2x": "because they are ",
   "ML3x": "They are all feeling ",
   "input1": ['harbor','school','farm'],
   "input2": ['being deported','tired','visiting their grandma'],
   "input3": ['sad','apprehensive','content'],

 },
 {//74
   "img": "images/PJG_10_reshaped.jpeg",
   "ML1": "The person that is carrying a poster of ",
   "ML2": " is a ",
   "ML3": ". He is carrying it because ",
   "ML1x": "The person that is carrying a poster of ",
   "ML2x": "is a ",
   "ML3x": "He is carrying it because ",
   "input1": ['an ad for tennis rackets','an athlete','tennis player'],
   "input2": ['billboard worker','worker','fan'],
   "input3": ['it is being installed','he is paid to put it up','he likes tennis'],

 },
 {//75
   "img": "images/PJG_11_reshaped.jpeg",
   "ML1": "This is a group of ",
   "ML2": " who are on their way to ",
   "ML3": ". The advertisement behind them is for ",
   "ML1x": "This is a group of ",
   "ML2x": "who are on their way to ",
   "ML3x": "The advertisement behind them is for ",
   "input1": ['people','mafia','people'],
   "input2": ['work','do business','see a movie'],
   "input3": ['an olympiad','sports','the movie'],

 },
 {//76
   "img": "images/PJG_12_reshaped.jpeg",
   "ML1": "The woman on the left is a ",
   "ML2": ". They are standing in/at ",
   "ML3": " and waiting for ",
   "ML1x": "The woman on the left is a ",
   "ML2x": "They are standing in/at ",
   "ML3x": "and waiting for ",
   "input1": ['mother','grandmother','nanny'],
   "input2": ['a street','a market','the road'],
   "input3": ['a taxi','the grandfather','for the parade to start'],

 },
 {//77
   "img": "images/PJG_13_reshaped.jpeg",
   "ML1": "These people are gathered at ",
   "ML2": " to watch ",
   "ML3": ". It is clear that they are feeling ",
   "ML1x": "These people are gathered at ",
   "ML2x": "to watch ",
   "ML3x": "It is clear that they are feeling ",
   "input1": ['a funeral','an event','a space station'], //Fix
   "input2": ['a parade','a big rocket depart','a rocket launch'], //FIX
   "input3": ['bored','anxious','intrigued'],

 },
 {//78
   "img": "images/PJG_14_reshaped.jpeg",
   "ML1": "The man in the center is holding a sign because ",
   "ML2": ". Around him, people are ",
   "ML3": ". They are standing in front of ",
   "ML1x": "The man in the center is holding a sign because ",
   "ML2x": "Around him, people are ",
   "ML3x": "They are standing in front of ",
   "input1": ['he is waiting for someone','he is homeless','he is protesting'],
   "input2": ['busy','ignoring him','looking at the art'],
   "input3": ['tall statues','posters','a large building'],

 },
 {//79
   "img": "images/PJG_15_reshaped.jpeg",
   "ML1": "These people are located in/at ",
   "ML2": ". One of the young children is talking to ",
   "ML3": " because ",
   "ML1x": "These people are located in/at ",
   "ML2x": "One of the young children is talking to ",
   "ML3x": "because ",
   "input1": ['Vietnam','the countryside','the mountains'],
   "input2": ['a soldier','a soldier','a soldier'],
   "input3": ['there is a war','she has not seen one before','these soldiers are invading their home'],

 },
 {//80
   "img": "images/SF_2_reshaped.jpeg",
   "ML1": "The child is ",
   "ML2": " on the side of the road because ",
   "ML3": ". He is reading ",
   "ML1x": "The child is ",
   "ML2x": "on the side of the road because ",
   "ML3x": "He is reading ",
   "input1": ['living','lying','resting'],
   "input2": ['he is homeless','he is homeless','he is relaxing'],
   "input3": ['a book','small book or pamphlet he stole from somewhere or maybe a hotel bible he took','some comics'],

 },
 {//81
   "img": "images/SF_3_reshaped.jpeg",
   "ML1": "This is a group of ",
   "ML2": " who are jumping because ",
   "ML3": ". The kid on the bicycle is thinking about ",
   "ML1x": "This is a group of ",
   "ML2x": "who are jumping because ",
   "ML3x": "The kid on the bicycle is thinking about ",
   "input1": ['young boys','children','kids'],
   "input2": ['they have nothing better to do and it seems like fun','it\'s something to do','there is no gym there'],
   "input3": ['whether to join in','what to do later on','his future'],

 },
 {//82
   "img": "images/SF_4_reshaped.jpeg",
   "ML1": "Outside of ",
   "ML2": ", this group is currently organizing ",
   "ML3": " on the ground for ",
   "ML1x": "Outside of ",
   "ML2x": "this group is currently organizing ",
   "ML3x": "on the ground for ",
   "input1": ['their house','a factory','a shack'],
   "input2": ['floors','coconuts','coconuts'],
   "input3": ['a house','drying','sale'],

 },
 {//83
   "img": "images/SF_5_reshaped.jpeg",
   "ML1": "This man is up in the tree in order to ",
   "ML2": ". He appears to be ",
   "ML3": ". He might be about to ",
   "ML1x": "This man is up in the tree in order to ",
   "ML2x": "He appears to be ",
   "ML3x": "He might be about to ",
   "input1": ['take down fruits','harvest','pick a coconut'],
   "input2": ['working','climbing','unstable'],
   "input3": ['take some fruits','fall','fall'],

 },
 {//84
   "img": "images/SF_6_reshaped.jpeg",
   "ML1": "These people are ",
   "ML2": " the tree because ",
   "ML3": ". The person in the background is running towards them in order to ",
   "ML1x": "These people are ",
   "ML2x": "the tree because ",
   "ML3x": "The person in the background is running towards them in order to ",
   "input1": ['hugging and holding','hugging','touching'],
   "input2": ['it is old and a miracle because of this','they are activists','they are praying'],
   "input3": ['also hug the tree','join in','join the prayer'],

 },
 {//85
   "img": "images/SF_7_BW_reshaped.jpeg",
   "ML1": "These people are sitting in/at a(n) ",
   "ML2": ". They are dressed in ",
   "ML3": " because ",
   "ML1x": "These people are sitting in/at a(n) ",
   "ML2x": "They are dressed in ",
   "ML3x": "because ",
   "input1": ['open seating area','soccer game','temple'],
   "input2": ['ponchos','trench coats','robes'],
   "input3": ['it is outside','it is raining','it is customary to do so inside the temple'],

 },
 {//86
   "img": "images/SF_8_BW_reshaped.jpeg",
   "ML1": "The men riding the scooters are ",
   "ML2": ". They are on their way to ",
   "ML3": " in order to ",
   "ML1x": "The men riding the scooters are ",
   "ML2x": "They are on their way to ",
   "ML3x": "in order to ",
   "input1": ['police','veterans','military'],
   "input2": ['work','a memorial site','a parade'],
   "input3": ['save the world','honor the dead and the cost of the war','celebrate their achievements'],

 },
 {//87
   "img": "images/SF_9_BW_reshaped.jpeg",
   "ML1": "This is an interaction between ",
   "ML2": ". The man with the cigarette is saying ",
   "ML3": " and the overall mood is ",
   "ML1x": "This is an interaction between ",
   "ML2x": "The man with the cigarette is saying ",
   "ML3x": "and the overall mood is ",
   "input1": ['groups of people','two drug dealers','two men'],
   "input2": ['something about his life','I don\'t care','how life is tough'], 
   "input3": ['joyful','euphoric','laid back'], 

 },
  {//88
   "img": "images/WB_3_reshaped.jpeg",
   "ML1": "This is taking place in/at/on ",
   "ML2": ". There is/are ",
   "ML3": " on the floor because ",
   "ML1x": "This is taking place in/at/on ",
   "ML2x": "There is/are ",
   "ML3x": "on the floor because ",
   "input1": ['ancient granary','mine','it is snowy'],
   "input2": ['seeds','sand','grain'],
   "input3": ['the bags were leaky','they are packing it','they are working'],

 },
 {//89
   "img": "images/WB_4_reshaped.jpeg",
   "ML1": "These children are in/on/at a(n) ",
   "ML2": " and are looking out at ",
   "ML3": ". The signs on their neck say ",
   "ML1x": "These children are in/on/at a(n) ",
   "ML2x": "and are looking out at ",
   "ML3x": "The signs on their neck say ",
   "input1": ['shop','train','a store owned by their parents'],
   "input2": ['the street','a cathedral','at other children playing'],
   "input3": ['they need to be adopted by someone','they are Christian','that they are second class citizens'],

 },
 {//90
   "img": "images/WB_5_reshaped.jpeg",
   "ML1": "This older man is gazing at ",
   "ML2": ". The buildings were once ",
   "ML3": ". Looking at the scene makes him think of ",
   "ML1x": "This older man is gazing at ",
   "ML2x": "The buildings were once ",
   "ML3x": "Looking at the scene makes him think of ",
   "input1": ['a demolished building','ruins','the sky'],
   "input2": ['houses','his home','his home'],
   "input3": ['the memories he has in that building','the past','of the war'],

 },
 {//91
   "img": "images/WB_6_reshaped.jpeg",
   "ML1": "The person on the right is a(n) ",
   "ML2": ". The person's leg is lifted to ",
   "ML3": ". The donkey is carrying ",
   "ML1x": "The person on the right is a(n) ",
   "ML2x": "The person's leg is lifted to ",
   "ML3x": "The donkey is carrying ",
   "input1": ['person','farmer','thief'],
   "input2": ['a horse','hold balance','steal the man on the left\'s stuff'],
   "input3": ['food','a sack','the man of the left\'s belongings'],

 },
 {//92
   "img": "images/WB_8_reshaped.jpeg",
   "ML1": "The donkey is carrying ",
   "ML2": " on its back because ",
   "ML3": ". The husband and wife are feeling ",
   "ML1x": "The donkey is carrying ",
   "ML2x": "on its back because ",
   "ML3x": "The husband and wife are feeling ",
   "input1": ['a coffin','a baby\'s coffin','something valuable'],
   "input2": ['he is strong','someone\'s baby died','it is too heavy for people to carry'],
   "input3": ['bad','sad and overwhelmed by the grief','nervous'],

 },
 {//93
   "img": "images/WB_9_reshaped.jpeg",
   "ML1": "The children are gathered at ",
   "ML2": " where they are looking at images of ",
   "ML3": ". They are feeling ",
   "ML1x": "The children are gathered at ",
   "ML2x": "where they are looking at images of ",
   "ML3x": "They are feeling ",
   "input1": ['a photo studio','a gallery','a funeral'],
   "input2": ['important men','men','people who have died'],
   "input3": ['inspired','uninterested','depressed'],

 },
 {//94
   "img": "images/WB_13_reshaped.jpeg",
   "ML1": "This group of boys is running because ",
   "ML2": ". They are in/at ",
   "ML3": ". They are feeling ",
   "ML1x": "This group of boys is running because ",
   "ML2x": "They are in/at ",
   "ML3x": "They are feeling ",
   "input1": ['of a disaster','they saw tourists','they are in a race'],
   "input2": ['a village','a small village','home'],
   "input3": ['scared','excited','happy'],


 },
 {//95
   "img": "images/WB_14_reshaped.jpeg",
   "ML1": "The girl is leaning down to ",
   "ML2": " because she is preparing for ",
   "ML3": ". She is feeling ",
   "ML1x": "The girl is leaning down to ",
   "ML2x": "because she is preparing for ",
   "ML3x": "She is feeling ",
   "input1": ['see herself in a mirror while doing her make-up',
   'take something out of her eye','pray'],
   "input2": ['a performance','bed','a big event'],
   "input3": ['nervous','lonely','overwhelmed'],

 },
 {//96
   "img": "images/WB_16_reshaped.jpeg",
   "ML1": "The figure in the middle of the tracks is ",
   "ML2": " and is standing in the center because ",
   "ML3": ". The figure is feeling ",
   "ML1x": "The figure in the middle of the tracks is ",
   "ML2x": "and is standing in the center because ",
   "ML3x": "The figure is feeling ",
   "input1": ['a child','a young woman','walking'],
   "input2": ['he is lost','she is trying to cross','she is exploring'],
   "input3": ['lonely','pain','adventurous'],

 },
 {//97
   "img": "images/WB_19_reshaped.jpeg",
   "ML1": "The young girl is holding a baby as she watches ",
   "ML2": ". The woman behind her is feeling ",
   "ML3": ". They are currently located in ",
   "ML1x": "The young girl is holding a baby as she watches ",
   "ML2x": "The woman behind her is feeling ",
   "ML3x": "They are currently located in ",
   "input1": ['something happen','television','her mother leave'],
   "input2": ['exhausted','sad','sad'],
   "input3": ['their home','a house','an orphanage'],

 },
 {//98
   "img": "images/CDK_1_reshaped.jpeg",
   "ML1": "The people in the car are ",
   "ML2": ". They are driving through deep water caused by ",
   "ML3": ". The people are feeling ",
   "ML1x": "The people in the car are ",
   "ML2x": "They are driving through deep water caused by ",
   "ML3x": "The people are feeling ",
   "input1": ['smiling and waving','evacuating','in big trouble'],
   "input2": ['a flood','flooding during a hurricane','a storm'], 
   "input3": ['gleeful','optimistic','weird'],

 },
 {//99
   "img": "images/JK_4_reshaped.jpeg",
   "ML1": "The group of men is playing for ",
   "ML2": ". The crowd behind them seems ",
   "ML3": ", and the musicians are feeling ",
   "ML1x": "The group of men is playing for ",
   "ML2x": "The crowd behind them seems ",
   "ML3x": "and the musicians are feeling ",
   "input1": ['a festival','a village','an orchestra'],
   "input2": ['excited','happy','angry'],
   "input3": ['worn down','cool','happy'],

 },
 {//99
  "img": "images/DH_9_reshaped.jpeg",
  "ML1": "The woman posing is a(n) ",
  "ML2": ". She is having her picture taken because she is ",
  "ML3": ". Everyone around her makes her feel ",
  "ML1x": "The woman posing is a(n) ",
  "ML2x": "She is having her picture taken because she is ",
  "ML3x": "Everyone around her makes her feel ",
  "input1": ['model','dancer','model'],
  "input2": ['posing','perfection','she is modeling a new swimsuit'],
  "input3": ['important','admired','self-conscious']
}
]